version: '3'

services:
  php:
    image: prooph/php:7.2-cli
    volumes:
      - ./:/app
    command: tail -f /dev/null
  gateway:
    image: prooph/php:7.2-fpm
    volumes:
      - .:/var/www
    command: tail -f /dev/null
  nginx:
    image: prooph/nginx:swoole
    ports:
    - 80:80
    - 443:443
    volumes:
    - ./app:/var/www
  eventstore:
    image: eventstore/eventstore:release-4.1.0
    ports:
      - 2113:2113
      - 1113:1113
    volumes:
      - "~/runtime/event-store:/var/lib/eventstore"
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "curl -sf http://localhost:2113/stats || exit 1"]
      interval: 5s
      timeout: 2s
    environment:
      - EVENTSTORE_RUN_PROJECTIONS=all